-- MySQL Script generated by MySQL Workbench
-- 06/23/14 11:18:53
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MobileAR_DB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `MobileAR_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MobileAR_DB` ;

-- -----------------------------------------------------
-- Table `MobileAR_DB`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MobileAR_DB`.`Owner` ;

CREATE TABLE IF NOT EXISTS `MobileAR_DB`.`Owner` (
  `owner_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  `id_or_reg_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`owner_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileAR_DB`.`VehicleFeatures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MobileAR_DB`.`VehicleFeatures` ;

CREATE TABLE IF NOT EXISTS `MobileAR_DB`.`VehicleFeatures` (
  `feature_id` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `colour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`feature_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileAR_DB`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MobileAR_DB`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `MobileAR_DB`.`Vehicle` (
  `vehivle_id` INT NOT NULL AUTO_INCREMENT,
  `number_plate` VARCHAR(10) NOT NULL,
  `Owner_owner_id` INT NOT NULL,
  `VehicleFeatures_feature_id` INT NOT NULL,
  `stolen` VARCHAR(10) NOT NULL,
  `fines` VARCHAR(10) NOT NULL,
  `roadworthy` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`vehivle_id`),
  INDEX `fk_Vehicle_Owner_idx` (`Owner_owner_id` ASC),
  INDEX `fk_Vehicle_VehicleFeatures1_idx` (`VehicleFeatures_feature_id` ASC),
  CONSTRAINT `fk_Vehicle_Owner`
    FOREIGN KEY (`Owner_owner_id`)
    REFERENCES `MobileAR_DB`.`Owner` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_VehicleFeatures1`
    FOREIGN KEY (`VehicleFeatures_feature_id`)
    REFERENCES `MobileAR_DB`.`VehicleFeatures` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileAR_DB`.`Detection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MobileAR_DB`.`Detection` ;

CREATE TABLE IF NOT EXISTS `MobileAR_DB`.`Detection` (
  `detection_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `location` VARCHAR(300) NOT NULL,
  `device_ip` VARCHAR(45) NOT NULL,
  `VehicleFeatures_feature_id` INT NOT NULL,
  PRIMARY KEY (`detection_id`),
  INDEX `fk_Detection_VehicleFeatures1_idx` (`VehicleFeatures_feature_id` ASC),
  CONSTRAINT `fk_Detection_VehicleFeatures1`
    FOREIGN KEY (`VehicleFeatures_feature_id`)
    REFERENCES `MobileAR_DB`.`VehicleFeatures` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileAR_DB`.`AuditLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MobileAR_DB`.`AuditLog` ;

CREATE TABLE IF NOT EXISTS `MobileAR_DB`.`AuditLog` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `table` VARCHAR(45) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `oldRow` VARCHAR(1000) NOT NULL,
  `newRow` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
